package games.platform.crud.gui;

import games.platform.connection.DataBase;
import games.platform.logger.AppLogger;
import games.platform.models.Discounts;
import games.platform.utils.DbGlobal;
import games.platform.utils.LoggerGlobal;
import java.util.ArrayList;
import java.util.Date;

import java.sql.SQLException;

public class DiscountForm extends javax.swing.JInternalFrame {

    DataBase db;

    private final String baseDiscountIdText = "ID do desconto: ";
    private final Discounts discounts;
    private final boolean newDiscount;

    public DiscountForm(Discounts discounts, boolean newGame) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.discounts = discounts;
        this.newDiscount = newGame;
        db = DbGlobal.getDb();

        initComponents();
        populateFields();
    }

    private void populateFields() {
        if (!newDiscount) {
            discountIdLabel.setText(baseDiscountIdText + discounts.getId());
            updateButton.setText("Atualizar");
        } else {
            updateButton.setText("Inserir");
        }

        gameId.setText(String.valueOf(discounts.getGame_id()));
        discountValue.setText(String.valueOf(discounts.getPrice_discount()));
        discountExpire.setValue(discounts.getExpire_date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountIdLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gameId = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        gameIdErrorLabel = new javax.swing.JLabel();
        responseLabel = new javax.swing.JLabel();
        discountValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateErrorLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        discountExpire = new javax.swing.JFormattedTextField();
        priceErrorLabel = new javax.swing.JLabel();

        setBorder(null);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 509));

        jLabel2.setText("Id do jogo");

        updateButton.setText("Atualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        gameIdErrorLabel.setForeground(new java.awt.Color(229, 57, 53));

        responseLabel.setForeground(new java.awt.Color(56, 142, 60));

        jLabel3.setText("Porcentagem do desconto");

        dateErrorLabel.setForeground(new java.awt.Color(229, 57, 53));

        jLabel4.setText("Data de Expiração (dia/mês/ano)");

        discountExpire.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        priceErrorLabel.setForeground(new java.awt.Color(229, 57, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discountValue)
                            .addComponent(priceErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameId, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gameIdErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(discountIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountExpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameIdErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        gameIdErrorLabel.setText("");

        int newGameId = 0;
        int newDiscountValue = 0;
        Date newDate = (Date) discountExpire.getValue();

        try {
            newDiscountValue = Integer.valueOf(discountValue.getText());
        } catch (NumberFormatException ex) {
            priceErrorLabel.setText("Erro ao transformar em número");
            return;
        }

        if (newDiscountValue < 0 || newDiscountValue > 100) {
            priceErrorLabel.setText("Valor de desconto inválido (0 a 100)");
            return;
        }

        try {
            newGameId = Integer.valueOf(gameId.getText());
        } catch (NumberFormatException ex) {
            gameIdErrorLabel.setText("Erro ao transformar em número");
            return;
        }

        if (newDate == null || !(newDate instanceof Date)) {
            dateErrorLabel.setText("Erro ao transformar em Date (dd/MM/yyyy)");
            return;
        }

        discounts.setGame_id(newGameId);
        discounts.setPrice_discount(newDiscountValue);
        discounts.setExpire_date(newDate);
        String response;
        if (newDiscount) {
            response = games.platform.crud.models.Discount.createDiscount(discounts, DbGlobal.getDb().getConnection());
        } else {
            response = games.platform.crud.models.Discount.updateDiscount(discounts, DbGlobal.getDb().getConnection());
        }
        responseLabel.setText(response);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateErrorLabel;
    private javax.swing.JFormattedTextField discountExpire;
    private javax.swing.JLabel discountIdLabel;
    private javax.swing.JTextField discountValue;
    private javax.swing.JTextField gameId;
    private javax.swing.JLabel gameIdErrorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel priceErrorLabel;
    private javax.swing.JLabel responseLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
